defaults:
  - dataloader: loader
  - dataset: FF++RealTrain
  - detector: dlib
  - encoder: SbiEff4
  - runner: MaskExtractor
  - transform: train
  - _self_

checkpoint:
author: iccv-anonymous

dataloader:
  num_workers: 0
  batch_size: 32

resume: True
verbose: False

hydra.job.chdir: False
